### ISSUE TITLE
Second Sprint

### ISSUE THREAD

**Issue by mceraso** [FordhamMuseumApp/SwiftRepo#25]
@minhchau273

Please see a gif of our second sprint under the /dev branch. What day are video presentations of our projects due? Launch day for our App with Fordham is on May 6th when there will be an opening festivus for the Student-Run Exhibition

**Comment by chieger** [comment]
Product Demo videos should be created by your classes demo day. In fact, many groups choose to present their video for the demo day and then field a few questions afterwards. You can also do a hybrid of video and live presentation.

Charlie
